name: Docker Image CI

on:
  push:
    branches: [ "main", "*" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-mcp

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Use docker-container driver with cache exporter
          driver: docker-container
          
      # Set up QEMU for multi-architecture support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login to registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            
      # Build base image once and cache it
      - name: Build base image for caching
        uses: docker/build-push-action@v5
        with:
          context: ./packages/markitdown-mcp
          push: true
          load: true
          tags: ${{ steps.meta.outputs.tags }}



